const SUPABASE_URL='https://lcvqaynpveajwdtjoleh.supabase.co';
const SUPABASE_KEY='sb_publishable_-RO3wUEL7FCFZ1Yw0BnMHA_srExU_iv';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'—';
let authMode='login', user=null, claimants=[], complaints=[];
function setAuthMode(mode){authMode=mode;$('tabLogin').className='btn '+(mode==='login'?'primary':'soft');$('tabSignup').className='btn '+(mode==='signup'?'primary':'soft');$('authSubmit').textContent=mode==='login'?'Entrar':'Criar conta';$('authPassword').autocomplete=mode==='login'?'current-password':'new-password';$('authMsg').textContent='';}
$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authMsg').textContent='Aguarde...';const email=$('authEmail').value.trim(),password=$('authPassword').value;let r=authMode==='login'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});if(r.error){$('authMsg').textContent=r.error.message;return}if(authMode==='signup'&&!r.data.session){$('authMsg').textContent='Conta criada. Confira seu e-mail para confirmar o cadastro.';return}await boot(r.data.user||r.data.session?.user)});
async function boot(u){user=u;if(!user)return showAuth();$('authScreen').classList.add('hidden');$('privateApp').classList.remove('hidden');$('userLabel').textContent=user.email||'';await loadAll();}
function showAuth(){$('privateApp').classList.add('hidden');$('authScreen').classList.remove('hidden')}
async function signOut(){await db.auth.signOut();user=null;claimants=[];complaints=[];showAuth()}
async function loadAll(){const [a,b]=await Promise.all([db.from('claimants').select('*').order('name'),db.from('complaints').select('*').order('created_at',{ascending:false})]);if(a.error||b.error){alert('Não foi possível carregar os dados.');return}claimants=a.data||[];complaints=b.data||[];renderAll()}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderAll();scrollTo(0,0)}
function renderClaimants(){const opts=claimants.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('claimant').innerHTML=opts;$('editClaimant').innerHTML=opts;$('filterClaimant').innerHTML='<option value="">Todos</option>'+opts;$('claimantList').innerHTML=claimants.length?claimants.map(c=>`<div class="card row"><span>${esc(c.name)}</span><button class="btn danger" style="flex:0 0 auto" onclick="deleteClaimant('${c.id}')">Excluir</button></div>`).join(''):'<div class="empty">Nenhum reclamante cadastrado.</div>'}
function openClaimants(){renderClaimants();claimantDialog.showModal()}
async function addClaimant(){const name=$('newClaimant').value.trim();if(!name)return;const r=await db.from('claimants').insert({user_id:user.id,name}).select().single();if(r.error){alert(r.error.message);return}$('newClaimant').value='';claimants.push(r.data);claimants.sort((a,b)=>a.name.localeCompare(b.name));renderClaimants()}
async function deleteClaimant(id){if(!confirm('Excluir este reclamante da lista? As reclamações antigas não serão apagadas.'))return;const r=await db.from('claimants').delete().eq('id',id);if(r.error){alert(r.error.message);return}claimants=claimants.filter(c=>c.id!==id);renderClaimants();renderComplaints()}
function sclass(s){return s==='Resolvida'?'done':s==='Precisa de ação'?'act':s==='Aguardando resposta'?'wait':'open'}
function card(c){return `<div class="card case" onclick="openDetail('${c.id}')"><div><h3>${esc(c.company)} — ${esc(c.subject)}</h3><div class="muted">${esc(c.claimant_name)} · ${esc(c.platform||'—')}<br>${c.protocol?'Protocolo: '+esc(c.protocol)+' · ':''}${fmt(c.complaint_date)}${c.next_action?'<br>Próxima ação: '+esc(c.next_action):''}</div></div><span class="pill ${sclass(c.status)}">${esc(c.status)}</span></div>`}
function renderHome(){$('mOpen').textContent=complaints.filter(c=>c.status!=='Resolvida').length;$('mWait').textContent=complaints.filter(c=>c.status==='Aguardando resposta').length;$('mAction').textContent=complaints.filter(c=>c.status==='Precisa de ação').length;$('mValue').textContent=money(complaints.reduce((s,c)=>s+Number(c.amount_recovered||0),0));$('recentList').innerHTML=complaints.length?complaints.slice(0,5).map(card).join(''):'<div class="card empty">Nenhuma reclamação cadastrada.</div>'}
function renderComplaints(){const fc=$('filterClaimant').value,fs=$('filterStatus').value;const arr=complaints.filter(c=>(!fc||c.claimant_id===fc)&&(!fs||c.status===fs));$('complaintsList').innerHTML=arr.length?arr.map(card).join(''):'<div class="card empty">Nenhum resultado.</div>'}
function days(d){if(!d)return null;const n=new Date();n.setHours(0,0,0,0);return Math.ceil((new Date(d+'T00:00:00')-n)/86400000)}
function renderDeadlines(){const arr=complaints.filter(c=>c.deadline&&c.status!=='Resolvida').sort((a,b)=>a.deadline.localeCompare(b.deadline));$('deadlineList').innerHTML=arr.length?arr.map(c=>{let x=days(c.deadline),cl='green',t=`Faltam ${x} dias`;if(x<0){cl='red';t=`Atrasado há ${Math.abs(x)} dias`}else if(x<=2){cl='red';t=x===0?'Vence hoje':`Faltam ${x} dias`}else if(x<=5)cl='yellow';return `<div class="card deadline" onclick="openDetail('${c.id}')"><div><b>${esc(c.company)} — ${esc(c.subject)}</b><div class="muted">${esc(c.claimant_name)} · ${fmt(c.deadline)}</div></div><span class="${cl}">${t}</span></div>`}).join(''):'<div class="card empty">Nenhum prazo pendente.</div>'}
async function openDetail(id){const c=complaints.find(x=>x.id===id);if(!c)return;const tr=await db.from('timeline_events').select('*').eq('complaint_id',id).order('event_date',{ascending:true}).order('created_at',{ascending:true});$('detailTitle').textContent=c.company+' — '+c.subject;$('detailBody').innerHTML=`<div class="muted" style="font-size:14px;line-height:1.8"><b>Reclamante:</b> ${esc(c.claimant_name)}<br><b>Status:</b> ${esc(c.status)}<br><b>Plataforma:</b> ${esc(c.platform||'—')}<br><b>Protocolo:</b> ${esc(c.protocol||'—')}<br><b>Data:</b> ${fmt(c.complaint_date)}<br><b>Prazo:</b> ${fmt(c.deadline)}<br><b>Valor envolvido:</b> ${money(c.amount_involved)}<br><b>Valor recuperado:</b> ${money(c.amount_recovered)}<br><b>Próxima ação:</b> ${esc(c.next_action||'—')}<br><b>Observações:</b> ${esc(c.notes||'—')}</div><h3>Linha do tempo</h3><div class="timeline">${(tr.data||[]).length?(tr.data||[]).map(e=>`<div class="event"><b>${fmt(e.event_date)} — ${esc(e.title)}</b><div class="muted">${esc(e.details||'')}</div><button class="btn danger" style="padding:6px 8px;margin-top:5px" onclick="deleteEvent('${e.id}','${id}')">Excluir</button></div>`).join(''):'<div class="muted">Nenhuma atualização.</div>'}</div><div class="actions"><button class="btn primary" onclick="startEdit('${id}')">Editar informações</button><button class="btn soft" onclick="addEvent('${id}')">+ Atualização</button><button class="btn danger" onclick="deleteComplaint('${id}')">Excluir reclamação</button></div>`;detailDialog.showModal()}
async function addEvent(id){const title=prompt('Título da atualização:');if(!title)return;const details=prompt('Observação (opcional):')||'';const event_date=prompt('Data (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!event_date)return;const r=await db.from('timeline_events').insert({user_id:user.id,complaint_id:id,event_date,title,details});if(r.error){alert(r.error.message);return}await openDetail(id)}
async function deleteEvent(id,cid){if(!confirm('Excluir esta atualização?'))return;const r=await db.from('timeline_events').delete().eq('id',id);if(r.error){alert(r.error.message);return}await openDetail(cid)}
function startEdit(id){const c=complaints.find(x=>x.id===id);if(!c)return;renderClaimants();$('editId').value=id;$('editClaimant').value=c.claimant_id||'';$('editCompany').value=c.company||'';$('editSubject').value=c.subject||'';$('editCategory').value=c.category||'';$('editPlatform').value=c.platform||'Outro';$('editProtocol').value=c.protocol||'';$('editDate').value=c.complaint_date||'';$('editDeadline').value=c.deadline||'';$('editStatus').value=c.status;$('editAmountInvolved').value=c.amount_involved||0;$('editAmountRecovered').value=c.amount_recovered||0;$('editNextAction').value=c.next_action||'';$('editNotes').value=c.notes||'';detailDialog.close();editDialog.showModal()}
$('editForm').addEventListener('submit',async e=>{e.preventDefault();const cid=$('editClaimant').value,cl=claimants.find(x=>x.id===cid);if(!cl)return alert('Cadastre um reclamante.');const id=$('editId').value;const data={claimant_id:cid,claimant_name:cl.name,company:$('editCompany').value.trim(),subject:$('editSubject').value.trim(),category:$('editCategory').value.trim()||null,platform:$('editPlatform').value,protocol:$('editProtocol').value.trim()||null,complaint_date:$('editDate').value||null,deadline:$('editDeadline').value||null,status:$('editStatus').value,amount_involved:Number($('editAmountInvolved').value||0),amount_recovered:Number($('editAmountRecovered').value||0),next_action:$('editNextAction').value.trim()||null,notes:$('editNotes').value.trim()||null};const r=await db.from('complaints').update(data).eq('id',id).select().single();if(r.error){alert(r.error.message);return}complaints=complaints.map(c=>c.id===id?r.data:c);editDialog.close();renderAll();openDetail(id)});
async function saveNewAttachments(complaintId){const input=$('newAttachments'),files=[...(input?.files||[])];for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){alert(`O arquivo ${file.name} não é uma imagem JPG, PNG ou WEBP.`);continue}if(file.size>10*1024*1024){alert(`O arquivo ${file.name} ultrapassa 10 MB.`);continue}const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${user.id}/${complaintId}/${crypto.randomUUID()}-${safeName}`;const up=await db.storage.from('complaint-prints').upload(path,file,{contentType:file.type,upsert:false});if(up.error){alert(`A reclamação foi salva, mas não foi possível enviar ${file.name}: ${up.error.message}`);continue}const ins=await db.from('complaint_attachments').insert({user_id:user.id,complaint_id:complaintId,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size});if(ins.error){await db.storage.from('complaint-prints').remove([path]);alert(`A reclamação foi salva, mas não foi possível vincular ${file.name}: ${ins.error.message}`)}}}
$('newForm').addEventListener('submit',async e=>{e.preventDefault();const cid=$('claimant').value,cl=claimants.find(x=>x.id===cid);if(!cl)return alert('Adicione um reclamante primeiro.');const data={user_id:user.id,claimant_id:cid,claimant_name:cl.name,company:$('company').value.trim(),subject:$('subject').value.trim(),category:$('category').value.trim()||null,platform:$('platform').value,protocol:$('protocol').value.trim()||null,complaint_date:$('complaintDate').value||null,deadline:$('deadline').value||null,status:$('status').value,amount_involved:Number($('amountInvolved').value||0),amount_recovered:Number($('amountRecovered').value||0),next_action:$('nextAction').value.trim()||null,notes:$('notes').value.trim()||null};const r=await db.from('complaints').insert(data).select().single();if(r.error){alert(r.error.message);return}await saveNewAttachments(r.data.id);complaints.unshift(r.data);e.target.reset();$('complaintDate').value=new Date().toISOString().slice(0,10);renderAll();go('complaints')});
async function deleteComplaint(id){if(!confirm('Excluir esta reclamação e toda a linha do tempo?'))return;const r=await db.from('complaints').delete().eq('id',id);if(r.error){alert(r.error.message);return}complaints=complaints.filter(c=>c.id!==id);detailDialog.close();renderAll()}
function renderAll(){renderClaimants();renderHome();renderComplaints();renderDeadlines()}
$('complaintDate').value=new Date().toISOString().slice(0,10);
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)boot(session.user);else showAuth();db.auth.onAuthStateChange((_e,s)=>{if(s&&!user)boot(s.user);if(!s&&user){user=null;showAuth()}})})();